#!/bin/bash

# Default FQBN and port name for Arduino Nano (ATmega328P with old bootloader)
fqbn="arduino:avr:nano:cpu=atmega328old"
port_name="/dev/ttyUSB0"

# Check if the required tools are installed
if ! command -v arduino-cli &>/dev/null; then
  echo "Arduino CLI is not installed. Please install it and try again."
  exit 1
fi

# Help message
display_help() {
  echo "Usage: $0 [OPTIONS] <sketch_directory>"
  echo "Options:"
  echo "  -b, --burn   Upload the sketch after compilation"
  echo "  -h, --help   Display this help message"
  exit 0
}


# Parse command line arguments
upload=false

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -b|--burn)
      upload=true
      shift
      ;;
    -h|--help)
      display_help
      ;;
    *)
      break
      ;;
  esac
done

# Check if the sketch directory is provided
if [ -z "$1" ]; then
  echo "Please provide the directory containing the Arduino sketch."
  display_help
fi

sketch_directory="$1"

# Change to the sketch directory
cd "$sketch_directory" || exit 1

# Compile the Arduino sketch
echo "Compiling sketch..."
compile_output=$(arduino-cli compile --fqbn "$fqbn" . 2>&1)  # Redirect stderr to stdout
exit_code = $?
# Upload the compiled sketch if the '-b' or '--burn' option is set
if [ $exit_code -eq 0]; then
  echo "Sketch compiled successfully"
  if [ "$upload" = true ]; then
    echo "Uploading sketch to board $fqbn on port $port_name"
    arduino-cli upload -p "$port_name" --fqbn "$fqbn"
  fi
else
  echo "Compilation failed with the following error:"
  echo "$compile_output"
fi

cd ..
